services:
  blockly-executor-1:
    environment:
      BLOCKLY_GRAAL_POOL_ENABLED: false

  blockly-executor-2:
    environment:
      BLOCKLY_GRAAL_POOL_ENABLED: false

  blockly-executor-3:
    environment:
      BLOCKLY_GRAAL_POOL_ENABLED: false
