global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blockly-executor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'blockly-executor-1:8086'
          - 'blockly-executor-2:8086'
    scrape_interval: 10s