spring:
  application:
    name: blockly-executor
  cloud:
    discovery:
      enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      auto-offset-reset: earliest
      properties:
        metric.reporters: io.micrometer.core.instrument.binder.kafka.KafkaClientMetrics
        metrics.sample.window.ms: 30000
    producer:
      properties:
        metric.reporters: io.micrometer.core.instrument.binder.kafka.KafkaClientMetrics
        metrics.sample.window.ms: 30000

  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public

  datasource:
    write:
      jdbc-url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://pgbouncer-write:6432/blockly?prepareThreshold=0}
      username: ${SPRING_DATASOURCE_USERNAME:blockly}
      password: ${SPRING_DATASOURCE_PASSWORD:blocklypwd}
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      auto-commit: true
      max-lifetime: 1800000
      idle-timeout: 600000
      pool-name: WritePool

    read:
      jdbc-url: ${SPRING_DATASOURCE_READ_URL:jdbc:postgresql://pgbouncer-read:6432/blockly?prepareThreshold=0}
      username: ${SPRING_DATASOURCE_READ_USERNAME:${SPRING_DATASOURCE_USERNAME:blockly}}
      password: ${SPRING_DATASOURCE_READ_PASSWORD:${SPRING_DATASOURCE_PASSWORD:blocklypwd}}
      driver-class-name: org.postgresql.Driver
      connection-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 5
      auto-commit: true
      max-lifetime: 1800000
      idle-timeout: 600000
      pool-name: ReadPool

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}


server:
  port: ${SERVER_PORT:8085}

blockly:
  kafka:
    topic: blockly-executor-procedures
    concurrency: 6
  graal:
    pool-size: 6

#Метрики
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  server:
    port: 8086
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: blockly-executor
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      slo:
        blockly_dao_read: 1ms,5ms,10ms,50ms,100ms,500ms,1s,2s,5s,10s,15s,20s,30s
        blockly_dao_write: 1ms,5ms,10ms,50ms,100ms,500ms,1s,2s,5s,10s,15s,20s,30s
        blockly_script_execution: 1ms,5ms,10ms,50ms,100ms,500ms,1s,2s,5s,10s,15s,20s,30s


#logging:
#  level:
#    org.apache.kafka.clients.admin: DEBUG
#    org.springframework.kafka: DEBUG