export const toolbox = {
    kind: 'categoryToolbox',
    contents: [
        {
            kind: 'category',
            name: 'Логика',
            colour: '#5C81A6',
            contents: [
                { kind: 'block', type: 'controls_if' },
                { kind: 'block', type: 'logic_compare' },
                { kind: 'block', type: 'logic_operation' },
                { kind: 'block', type: 'logic_negate' },
                { kind: 'block', type: 'logic_boolean' },
                { kind: 'block', type: 'logic_null' },
                { kind: 'block', type: 'logic_ternary' },
            ],
        },
        {
            kind: 'category',
            name: 'Циклы',
            colour: '#5CA65C',
            contents: [
                { kind: 'block', type: 'controls_repeat_ext' },
                { kind: 'block', type: 'controls_whileUntil' },
                { kind: 'block', type: 'controls_for' },
                { kind: 'block', type: 'controls_forEach' },
                { kind: 'block', type: 'controls_flow_statements' },
            ],
        },
        {
            kind: 'category',
            name: 'Математика',
            colour: '#5CA65C',
            contents: [
                { kind: 'block', type: 'math_number' },
                { kind: 'block', type: 'math_arithmetic' },
                { kind: 'block', type: 'math_single' },
                { kind: 'block', type: 'math_round' },
                { kind: 'block', type: 'math_trig' },
                { kind: 'block', type: 'math_constant' },
                { kind: 'block', type: 'math_number_property' },
                { kind: 'block', type: 'math_on_list' },
                { kind: 'block', type: 'math_modulo' },
                { kind: 'block', type: 'math_random_int' },
                { kind: 'block', type: 'math_random_float' },
            ],
        },
        {
            kind: 'category',
            name: 'Текст',
            colour: '#A65C5C',
            contents: [
                { kind: 'block', type: 'text_limited' },
                { kind: 'block', type: 'text_multiline' },
                { kind: 'block', type: 'text_join' },
                { kind: 'block', type: 'text_append' },
                { kind: 'block', type: 'text_length' },
                { kind: 'block', type: 'text_isEmpty' },
                { kind: 'block', type: 'text_indexOf' },
                { kind: 'block', type: 'text_charAt' },
                { kind: 'block', type: 'text_getSubstring' },
                { kind: 'block', type: 'text_changeCase' },
                { kind: 'block', type: 'text_trim' },
                { kind: 'block', type: 'text_print' },
                { kind: 'block', type: 'text_reverse' },
            ],
        },
        {
            kind: 'category',
            name: 'Списки',
            colour: '#745BA6',
            contents: [
                { kind: 'block', type: 'lists_create_empty' },
                { kind: 'block', type: 'lists_create_with' },
                { kind: 'block', type: 'lists_repeat' },
                { kind: 'block', type: 'lists_reverse' },
                { kind: 'block', type: 'lists_isEmpty' },
                { kind: 'block', type: 'lists_length' },
                { kind: 'block', type: 'lists_indexOf' },
                { kind: 'block', type: 'lists_getIndex' },
                { kind: 'block', type: 'lists_setIndex' },
                { kind: 'block', type: 'lists_getSublist' },
                { kind: 'block', type: 'lists_split' },
                { kind: 'block', type: 'lists_sort' },
            ],
        },
        {
            kind: 'category',
            name: 'Переменные',
            colour: '#A65C81',
            custom: 'VARIABLE',
        },
        {
            kind: 'category',
            name: 'Функции',
            colour: '#995499',
            custom: 'PROCEDURE',
        },
        {
            kind: 'category',
            name: 'Даты',
            colour: '#4A90D9',
            contents: [
                { kind: 'block', type: 'date_now' },
                { kind: 'block', type: 'date_today' },
                { kind: 'block', type: 'date_time_now' },
                { kind: 'block', type: 'date_create' },
                { kind: 'block', type: 'date_get' },
                { kind: 'block', type: 'date_set' },
                { kind: 'block', type: 'date_add' },
                { kind: 'block', type: 'date_subtract' },
                { kind: 'block', type: 'date_format' },
                { kind: 'block', type: 'date_diff' },
                { kind: 'block', type: 'date_compare' },
            ],
        },
        {
            kind: 'category',
            name: 'Действия',
            colour: '#209FDB',
            contents: [
                { kind: 'block', type: 'action_execute' },
            ],
        },
        {
            kind: 'category',
            name: 'Массивы данных',
            colour: '#0078D7',
            contents: [
                { kind: 'block', type: 'array_length' },
                { kind: 'block', type: 'array_get' },
                { kind: 'block', type: 'array_forEach' },
                { kind: 'block', type: 'array_filter' },
                { kind: 'block', type: 'array_map' },
                { kind: 'block', type: 'array_sum' },
            ],
        },

    ],
}